- .gitignore
- README.md
- flask/app.py
- flask/requirements.txt
- flask/templates/My-Form.html
- flask/templates/form-result.html
#16  Basic framework for a form was created, also added documentation on how to create a file w/ the proper values to run the app locally.  I think 1 thing I just added seems *not good* for anything other than development & I'll leave a comment on it but yup we did the thing :1st_place_medal:
> Flask forms

- PUAMapp/App.js
- PUAMapp/ContactPage.js
- PUAMapp/ExplorePage.js
- PUAMapp/GalleryPage.js
- PUAMapp/HomePage.js
Scaffolded a few pages for future work
> HomePage -> (ExplorePage, GalleryPage, ContactPage)

- PUAMapp/HomePage.js
- PUAMapp/app.json
- PUAMapp/package.json
-----
@chris-anderson67 @suruchidev @ymao03
> style the buttons a bit

- .expo/packager-info.json
- .expo/settings.json
- PUAMapp/GalleryPage.js
- PUAMapp/package-lock.json
Issue no 30: the react native map function loops through an array of image urls stored in state and displays them using flex box
> modified gallery page to use flexbox to display images

- PUAMapp/App.js
- PUAMapp/ExplorePage.js
- PUAMapp/MuralInfoPage.js
Artwork name, artist title, a button for toggling showing the description
> A basic mural page

- PUAMapp/GalleryPage.js
Layout of gallery page finished. 
Not sure how it looks on different phones though.
> Issue 30: implemented gallery page layout design 

- PUAMapp/HomePage.js
Changed the way the home page image looks woo 🍏
> Fixed the stretched image

- PUAMapp/ExplorePage.js
Moved around the hard-corded markers & got the tooltip popping up with rerouting on click 👍
> Tooltip Party

- PUAMapp/GalleryPage.js
> pass the mural to the muralInfo page

- PUAMapp/ContactPage.js
- PUAMapp/ExplorePage.js
- PUAMapp/GalleryPage.js
- PUAMapp/HomePage.js
- PUAMapp/MuralInfoPage.js
> Added headers to all of the pages

- PUAMapp/MuralInfoPage.js
also now the entire page is one big button..
> changed open and close buttons for description

- PUAMapp/ContactPage.js
- PUAMapp/ExplorePage.js
- PUAMapp/GalleryPage.js
- PUAMapp/HomePage.js
- PUAMapp/MuralInfoPage.js
- PUAMapp/colors.js
look @ all the pretty colors! 🌈
> Added color file & changed colors in the app

- PUAMapp/ContactPage.js
- PUAMapp/package.json
This is the best contact page. All other contact pages wish they were this contact page.
> a very lazy contact/info page

- PUAMapp/HomePage.js
- PUAMapp/colors.js
- PUAMapp/package-lock.json
Fixed up those button colors & those ~margins~ 🙆
> Got the buttons to be the right color & fixed the margins

- PUAMapp/App.js
- PUAMapp/package-lock.json
Also the status bar text on iphone is now white 👍
> Fixing android status bar overlap

- flask/app.py
because it needs to be seeecreeet
shhhhhhhhh
> Make flask use a secret key independent of the flask app key

- flask/templates/My-Form.html
- flask/templates/artist-form.html
- flask/templates/base.html
- flask/templates/disp-all.html
- flask/templates/form-result.html
- flask/templates/validation-form.html
@chris-anderson67 @barieom @bmfahey
> Base templating, links on every page

- PUAMapp/App.js
> Disable swiping back from the home page (no return to the splash screen)

- flask/app.py
Now randos can't delete our precious murals
> added annotation to require auth for deletion

- flask/app.py
> logout url

- flask/templates/base.html
> logout link

- PUAMapp/ContactPage.js
- PUAMapp/ExplorePage.js
- PUAMapp/GalleryPage.js
- PUAMapp/HomePage.js
- PUAMapp/MuralInfoPage.js
Should be all set aside from the Info page
> Fix Android Nav Bar, Status Bar, Crash

- PUAMapp/ContactPage.js
- added an if else statement to make styles object different based on if the phone is android or iOS
- changed the android styles object to look like the proposed designs
NOTE: styles object is no longer a constant.
> android changes made to contact page

- flask/app.py
> Don't try to coerce uuids into ints, kids

- PUAMapp/SplashScreen.js
#146 Now there's a pink loading symbol on the splash screen below the logo! Hooray! :eagle:
> Added loading symbol & style for it on the splash screen

- PUAMapp/MuralInfoPage.js
#147 -- Mural description is gone, artist bio is replacing it -- artist city is at the top of the read more section now as well! 💇 
(also it looks like my editor deleted some extra spaces that were in the file??)
> Got rid of mural description, added in artist bio & city

- PUAMapp/ContactPage.js
#151 -- donate button now looks fine on ios but the background color & shadow don't pop up on android 😿
> Fixed donate button for ios

- flask/app.py
- flask/templates/base.html
- flask/templates/disp-all-artists.html
- flask/templates/edit-artist
- flask/templates/edit-artist.html
Can view artists and edit artists now (still working on delete)
> Edit murals

- flask/app.py
- flask/templates/base.html
- flask/templates/disp-all-artists.html
- alerts if unsuccessful 
#182 
@chris-anderson67 @airwayneeee
> delete an artist if it doesn't have any murals

- flask/app.py
- flask/templates/My-Form.html
- flask/templates/artist-form.html
- flask/templates/edit-artist.html
artist bio and/or mural description can be empty- artist photo removed
> artist bio and/or mural description can be empty- artist photo removed

- PUAMapp/ContactPage.js
- PUAMapp/MuralInfoPage.js
Also email button should copy email
> Properly display long descriptions

- PUAMapp/MuralInfoPage.js
- PUAMapp/package.json
Not perfect, but think it looks better than before and reasonably okay
lmk what you think
@chris-anderson67 
#189
> Better animation for MuralInfoPage

- PUAMapp/.gitignore~
- PUAMapp/App.js
- PUAMapp/ContactPage.js
- PUAMapp/ExplorePage.js
- PUAMapp/GalleryPage.js
- PUAMapp/HomePage.js
- PUAMapp/MuralInfoPage.js
- PUAMapp/SplashScreen.js
- PUAMapp/redux.js
Just apply an auto-format to our js code
> Format code

- PUAMapp/ContactPage.js
- PUAMapp/ExplorePage.js
- PUAMapp/GalleryPage.js
- PUAMapp/MuralInfoPage.js
Read more button which is easier to see.
Also make our other buttons manually instead of using pngs. We'll delete the unused png files when we do a cleanup at the end of the semester.
> Read more button

- PUAMapp/ContactPage.js
- PUAMapp/ExplorePage.js
- PUAMapp/GalleryPage.js
- PUAMapp/MuralInfoPage.js
The url for both bug report and tour request is not correct. @chris-anderson67
> Add bug report and tour request bottom

- PUAMapp/ContactPage.js
> removed THE from contacts

- PUAMapp/ExplorePage.js
- PUAMapp/app.json
Remove timeout, bump version, remove infinite nav stack
> Version bump again

- PUAMapp/.gitignore
- PUAMapp/App.js
- PUAMapp/app.json
- PUAMapp/package.json
And disable error report in development mode
> Adding sentry

- PUAMapp/App.js
- PUAMapp/ContactPage.js
- PUAMapp/GalleryPage.js
- PUAMapp/HomePage.js
- PUAMapp/MuralInfoPage.js
- PUAMapp/SplashScreen.js
- PUAMapp/utilities.js
* Extract constants
* Optimize imports
* Fix inspection errors
* Extract isIOS and isIphonX into a Utilities module
> Lint error fixes
